title: "Cult of Ferris"
description: "An Introduction to Programming with Rust"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: ""
url: "https://cult.undertheprinter.com"
permalink: /:title/
author: "TechnoElf"

include: ["_pages"]

plugins:
  - jekyll-sitemap

highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
sass:
  sass_dir: _sass
  style: compressed
